### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by ghost** [NicolasGuilloux/KGet-Integrator#1]
Please include a LICENSE file. If it's work borrowed and adapted then it needs to be GPL v3 since that is what uGet Integrator uses. Otherwise, please include LICENSE so that your integrator can be included for packaging into distributions.

**Comment by NicolasGuilloux** [comment]
Hello,

Yes you're right, I added this project too quickly and forgot to complete the git. Thank you ! :)
