### ISSUE TITLE
Unable to connect with kget-integrator

### ISSUE THREAD

**Issue by rafaelmr2** [NicolasGuilloux/KGet-Integrator#2]
Hi,

I have installed kget-integrator in Firefox 63.0.1 on Fedora 29. I copied file "com.kgetdm.firefox.json" to "/usr/lib/mozilla/native-messaging-hosts" and "kget-integrator" to "/usr/bin".

Still get the error "Unable to connect with kget-integrator"

Thanks

**Comment by NicolasGuilloux** [comment]
Hi !

I did this addon really quickly, I'm not surprised that it does not work on every computer ;)
Sadly, I will struggle to help you as I only adapted the uGet integrator to KGet.

But still, we can dig a little to find this issue. 

- Can you check if `/usr/bin/kget-integrator` has the right to execute ?
- Can you try to execute it ? You should see nothing in the terminal except a running program...

**Comment by rafaelmr2** [comment]
Hi,

Yes, has the X permission:
-rwxr-xr-x. 1 root root 3017 nov 16 20:08 /usr/bin/kget-integrator

Yes, I run and do nothing.

Thanks.

**Comment by Sweetchuck** [comment]
Same here.

`$(which python3) --version`
> Python 3.6.5


`ls -lA /usr/lib/mozilla/native-messaging-hosts`
> total 4.0K
> -rw-r--r-- 1 root root 236 2018-12-20 10:07 com.kgetdm.firefox.json

`ls -lA /usr/bin/kget-integrator`
> -rwxr-xr-x 1 root root 3.0K 2018-12-20 10:15 /usr/bin/kget-integrator

`kget --version`
> kget 18.12.0

openSUSE Tumbleweed
FireFox 63.0.3 (64-bit)

**Comment by Sweetchuck** [comment]
It works with __Mozilla Firefox Developer Edition 65.0b5 64bit__

**Comment by rafaelmr2** [comment]
I'm using Manjaro KDE now and it works in Firefox 64.

**Comment by R3D9477** [comment]
I've same error:
```
$ $(which python3) --version
Python 3.6.8

$ ls -lA /usr/lib/mozilla/native-messaging-hosts
total 4
-rw-r--r-- 1 root root 240 Jul  9 20:33 org.kde.plasma.browser_integration.json

$ ls -lA /usr/bin/kget-integrator
-rwxr-xr-x 1 root root 3017 Jul 18 13:23 /usr/bin/kget-integrator

$ firefox --version
Mozilla Firefox 68.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.16
Release:        18.04
Codename:       bionic
```
And no messages/warning/errors after it launched manually:
```
$ kget-integrator

```

**Comment by NicolasGuilloux** [comment]
Hi ! I'm back, sorry for the huge delay !
@r3d9u11 You forgot to put the configuration file in the native-messaging-hosts I guess.
@Sweetchuck Can you try with a more recent Firefox ?

I just tried it on a clean Manjaro with Firefox 68 and it works just well.

**Comment by Sweetchuck** [comment]
Is this file really needs to be here? ;-)
https://github.com/NicolasGuilloux/KGet-Integrator/blob/master/Firefox/Firefox.zip

**Comment by NicolasGuilloux** [comment]
Ah ah no! I'll fix this stupid mistake :p

**Comment by Sweetchuck** [comment]
# My installer script

```zsh
#!/usr/bin/env zsh

set -x
set -e

cp ./kget-integrator /usr/bin/kget-integrator
chmod +x             /usr/bin/kget-integrator
chown root:root      /usr/bin/kget-integrator

mkdir -p /etc/chromium/native-messaging-hosts
cp \
	./Conf/com.kgetdm.chrome.json \
	/etc/chromium/native-messaging-hosts/com.kgetdm.chrome.json
chown root:root /etc/chromium/native-messaging-hosts/com.kgetdm.chrome.json


mkdir -p /usr/lib/mozilla/native-messaging-hosts
cp \
	./Conf/com.kgetdm.firefox.json \
	/usr/lib/mozilla/native-messaging-hosts/com.kgetdm.firefox.json
chown root:root /usr/lib/mozilla/native-messaging-hosts/com.kgetdm.firefox.json
```

`$ sudo zsh ./install.zsh`

# FireFox Developer Edition 69.0b4 (64-bit)

Add-on installed from: https://addons.mozilla.org/en-US/firefox/addon/kget-integration
Result: :smile: 


# Chromium 75.0.3770.100 (openSUSE Build) (64-bit)

Extension installed: with "Load unpacked" from the Git repository
2019-07-20 00:16:44 +0200 37094a05575c678ef4ac9f7cfabd40210678d06d

> Unable to connect with kget-integrator

> Unchecked runtime.lastError: Access to the specified native messaging host is forbidden.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)

![Screenshot_20190720_115815](https://user-images.githubusercontent.com/591103/61577295-b60c4180-aae5-11e9-889e-d43279879ba7.png)

**Comment by NicolasGuilloux** [comment]
Can you check the rights of the configuration fie for Chrome ?
I did not do the `chown root:root` on it, and it's working on my computer for both Chromium and Brave.

I forgot something maybe: can you follow the indications of [this link](https://stackoverflow.com/questions/20216224/chrome-native-messaging-error-access-to-the-specified-native-messaging-host-i) please ?

**Comment by Sweetchuck** [comment]
Yes. That worked.

Install steps for Chromium
1.  Add the extension with enabled "Developer mode" and "Load unpacked"
2. Copy to clipboard the unique extension id. (long ugly hash chrome://extensions/ )
3. `cp ./Conf/com.kgetdm.chrome.json /etc/chromium/native-messaging-hosts/com.kgetdm.chrome.json`
4. `$EDITOR /etc/chromium/native-messaging-hosts/com.kgetdm.chrome.json`
  Change `allowed_origins.0` to `chrome-extension://CTRL+V/`

**Comment by R3D9477** [comment]
> Hi ! I'm back, sorry for the huge delay !
> @r3d9u11 You forgot to put the configuration file in the native-messaging-hosts I guess.
> @Sweetchuck Can you try with a more recent Firefox ?
> 
> I just tried it on a clean Manjaro with Firefox 68 and it works just well.

Yes, you are right.
Works fine for me, thank you!

**Comment by NicolasGuilloux** [comment]
I supposed I should pack the Chromium extension to work out of the box. I'm working on it to do a continuous integration ! ;)

**Comment by NicolasGuilloux** [comment]
So I installed the CI but I have now issues with the Chromium extension packaging reported in #5. If someone finds out where this issue come from, please let me know :)
