### ISSUE TITLE
wish: Start immediately a download with kget

### ISSUE THREAD

**Issue by sotel** [NicolasGuilloux/KGet-Integrator#3]
Maybe you would like to start the download of a file without using kgets gui. Than use:

qdbus org.kde.kget /KGet org.kde.kget.main.addTransfer $URL $DOWNLOADFOLDER true

instead of kget. Replace $URL with the variable which contains the url of a file you want to download and $DOWNLOADFOLDER by the default download folder e.g. ${HOME}/Downloads.

**Comment by NicolasGuilloux** [comment]
Hello !
Sorry for the delay, I was very busy for a while. Now I'm back again :p
That is very good ! It could be an option.
I will try to add it right now. :)
