### ISSUE TITLE
Needs an AUR package

### ISSUE THREAD

**Issue by erayerdin** [NicolasGuilloux/KGet-Integrator#6]
I'm just adding it here as TODO for either dev or community (if anyone sees this). It would be so great to have this thing as an AUR hosted package for Arch-based distros.

I would have liked to do that yet I will be unavailable for a long time and would not want to have AUR package be orphaned.

**Comment by NicolasGuilloux** [comment]
Hi!

It is in my looooong, very long list of To-do but thanks for reminding me :-P

Actually I began to make an AUR package, it is not finished yet and I dropped it. Since there are a few people using the integrator, I'll do it.

**Comment by NicolasGuilloux** [comment]
Here is the core script: https://aur.archlinux.org/packages/kget-integrator/
The browsers native message:  https://aur.archlinux.org/packages/kget-integrator-browsers/
