### ISSUE TITLE
A tutorial please for non dev please

### ISSUE THREAD

**Issue by promeneur** [NicolasGuilloux/KGet-Integrator#7]
Hello

Firefox 71

I am not a dev.

Where and how to get the files ?
- kget-integrator
- com.kgetdm.firefox.json

It is not clear what folder to create in /usr/lib/mozilla/

a script which get these files and put them at the right place would be welcome

thanks

**Comment by NicolasGuilloux** [comment]
Hi!

I will update the ReadMe to give more information ;)
