### ISSUE TITLE
copy com.kgetdm.firefox.json to /usr/lib/mozilla/native-messaging-hosts/, not for openSuse

### ISSUE THREAD

**Issue by promeneur** [NicolasGuilloux/KGet-Integrator#9]
Firefox 71, openSuse leap 15.1 Argon
For openSuse we must 

copy com.kgetdm.firefox.json to /usr/lib64/mozilla/native-messaging-hosts/

**Comment by NicolasGuilloux** [comment]
Hello there!

This is kinda weird because the `/usr/lib` is supposed to point to `/usr/lib64`. I'll change the ReadMe, but actually you should not put it directly into `/usr/lib64` but rather put it in `/usr/lib` as it should be platform agnostic, and create a symlink if you need to.

```
mkdir -p /usr/lib/mozilla/native-messaging-hosts
cp Conf/com.kgetdm.firefox.json /usr/lib/mozilla/native-messaging-hosts

# If it does not work and need to put it in the lib64 folder
mkdir -p /usr/lib64/mozilla/native-messaging-hosts
ln -s /usr/lib/mozilla/native-messaging-hosts/com.kgetdm.firefox.json /usr/lib64/mozilla/native-messaging-hosts
```
